version: '3.7'
services:
  db:
    image: mariadb:10.2
    restart: always
    environment:
      - MARIADB_DATABASE=CC
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: