CREATE OR REPLACE DATABASE CC;

USE CC;

CREATE OR REPLACE TABLE DECKS (
    id UUID PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL
);

CREATE OR REPLACE TABLE USERS(
	id UUID PRIMARY KEY,
	pseudo VARCHAR(255) NOT NULL,
	token INT NOT NULL,
	deck UUID REFERENCES DECKS(id)
);

CREATE OR REPLACE TABLE HEROES (
    id UUID PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    healthPoints INT NOT NULL,
    power INT NOT NULL,
    armor INT NOT NULL,
    speciality VARCHAR(255) NOT NULL,
    rarity VARCHAR(255) NOT NULL
);

CREATE OR REPLACE TABLE CARDS (
    id UUID PRIMARY KEY,
    deck UUID REFERENCES DECKS (id),
    hero UUID REFERENCES HEROES (id),
    `level` INT NOT NULL,
    experiencePoints INT NOT NULL
);

CREATE OR REPLACE TABLE COMBATS (
    id UUID PRIMARY KEY,
    user1 UUID REFERENCES USERS(id),
    card1 UUID REFERENCES CARDS(id),
    user2 UUID REFERENCES USERS(id),
    card2 UUID REFERENCES CARDS(id),
    winner UUID REFERENCES USERS(id) 
);