CREATE OR REPLACE DATABASE CC;

USE CC;

CREATE OR REPLACE TABLE DECKS (
    id INT PRIMARY KEY,
	`name` VARCHAR(255)
);

CREATE OR REPLACE TABLE HEROES (
    id INT PRIMARY KEY
);

CREATE OR REPLACE TABLE CARDS (
    id INT PRIMARY KEY ,
    deck INT REFERENCES DECKS (id),
    heroes INT REFERENCES HEROES (id)
)